# ./k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-teacher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-teacher
  template:
    metadata:
      labels:
        app: client-teacher
    spec:
      containers:
        - name: client-teacher
          image: client-teacher:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: APP_ENV
              value: "minikube"

---
apiVersion: v1
kind: Service
metadata:
  name: client-teacher-service
spec:
  type: NodePort
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30301
  selector:
    app: client-teacher
