# ./k8s/api-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-student
  template:
    metadata:
      labels:
        app: client-student
    spec:
      containers:
        - name: client-student
          image: client-student:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-student-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: client-student
