apiVersion: v1
kind: Service
metadata:
  name: mongo-config
  labels:
    app: mongo
spec:
  ports:
  - port: 27019
    name: mongo
  clusterIP: None
  selector:
    role: mongo
    config-server: "true"
